FROM mambaorg/micromamba:latest

COPY --chown=$MAMBA_USER:$MAMBA_USER envfiles/deepTarget.yml /tmp/env.yml

RUN micromamba install -y -f /tmp/env.yml && \
    micromamba install -y -n base -c conda-forge git && \
    micromamba clean --all --yes

ARG MAMBA_DOCKERFILE_ACTIVATE=1