FROM continuumio/miniconda3:latest as build

RUN apt-get update && apt-get install --no-install-recommends -y build-essential libz-dev libcurl3-dev libarchive-dev gcc \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
    
RUN mkdir -p /app

ADD ./envfiles/sharedpy3keras2tf2.yml /app/

RUN conda update conda && \
    conda install -y -c conda-forge conda-libmamba-solver && \
    conda env create -n kipoi-shared__envs__kipoi-py3-keras2-tf2 -f ./app/sharedpy3keras2tf2.yml --experimental-solver=libmamba && \ 
    conda clean -afy

FROM continuumio/miniconda3:latest 

RUN apt-get update && apt-get install --no-install-recommends -y  ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app
COPY --from=build /opt/conda/envs/kipoi-shared__envs__kipoi-py3-keras2-tf2 /opt/conda/envs/kipoi-shared__envs__kipoi-py3-keras2-tf2

RUN echo "source activate kipoi-shared__envs__kipoi-py3-keras2-tf2" > ~/.bashrc
ENV PATH /opt/conda/envs/kipoi-shared__envs__kipoi-py3-keras2-tf2/bin:$PATH

