FROM kipoi-base-env:0.1

SHELL ["conda", "run", "-n", "kipoi-env", "/bin/bash", "-c"]

RUN kipoi env create CleTimer --verbose

RUN echo "source activate kipoi-CleTimer" > ~/.bashrc
ENV PATH /opt/conda/envs/kipoi-CleTimer/bin:$PATH

SHELL ["conda", "run", "-n", "kipoi-CleTimer", "/bin/bash", "-c"]

RUN conda install -c anaconda cython && pip install numpy==1.16.2 && pip install keras==2.2.4