FROM continuumio/miniconda3:latest

RUN apt-get update && apt-get install -y build-essential libz-dev libcurl3-dev libarchive-dev gcc

RUN conda install --yes -c conda-forge hdf5=1.10.6 pkgconfig

RUN mkdir -p /app

ADD dockerfiles/environment.kipoi.yml /app/environment.kipoi.yml

RUN conda env create -f /app/environment.kipoi.yml

RUN echo "source activate kipoi-env" > ~/.bashrc
ENV PATH /opt/conda/envs/kipoi-env/bin:$PATH

RUN conda clean -afy