FROM haimasree/kipoi-docker:kipoi-base-env

SHELL ["conda", "run", "-n", "kipoi-env", "/bin/bash", "-c"]

RUN kipoi env create Xpresso --verbose

RUN echo "source activate kipoi-Xpresso" > ~/.bashrc
ENV PATH /opt/conda/envs/kipoi-Xpresso/bin:$PATH

SHELL ["conda", "run", "-n", "kipoi-Xpresso", "/bin/bash", "-c"]