FROM haimasree/kipoi-docker:kipoi-base-env

SHELL ["conda", "run", "-n", "kipoi-env", "/bin/bash", "-c"]

RUN kipoi env create KipoiSplice --verbose

RUN echo "source activate kipoi-KipoiSplice" > ~/.bashrc
ENV PATH /opt/conda/envs/kipoi-KipoiSplice/bin:$PATH

SHELL ["conda", "run", "-n", "kipoi-KipoiSplice", "/bin/bash", "-c"]