FROM continuumio/miniconda3:4.8.2

RUN apt-get update && \
    apt-get install -y build-essential libz-dev libcurl3-dev

RUN mkdir -p /app

ADD dockerfiles/environment.kipoi.yml /app/environment.kipoi.yml

RUN conda env create -f /app/environment.kipoi.yml

RUN echo "source activate kipoi-env" > ~/.bashrc
ENV PATH /opt/conda/envs/kipoi-env/bin:$PATH

RUN conda clean -afy