FROM haimasree/kipoi-docker:kipoi-base-env

COPY ./envfiles/mmsplicemtsplice.yml ./app

RUN conda env create -n kipoi-MMSplice__mtsplice -f ./app/mmsplicemtsplice.yml

RUN echo "source activate kipoi-MMSplice__mtsplice" > ~/.bashrc
ENV PATH /opt/conda/envs/kipoi-MMSplice__mtsplice/bin:$PATH

SHELL ["conda", "run", "-n", "kipoi-MMSplice__mtsplice", "/bin/bash", "-c"]