FROM mambaorg/micromamba:latest

COPY --chown=$MAMBA_USER:$MAMBA_USER envfiles/mmsplice-mtsplice.yml /tmp/env.yml

RUN micromamba install -y -f /tmp/env.yml --verbose && \
    micromamba install -y -n base -c conda-forge git && \
    micromamba clean --all --yes && \
    find /opt/conda/ -follow -type f -name '*.a' -delete && \
    find /opt/conda/ -follow -type f -name '*.js.map' -delete

ARG MAMBA_DOCKERFILE_ACTIVATE=1