FROM haimasree/kipoi-docker:kipoi-base-env

SHELL ["conda", "run", "-n", "kipoi-env", "/bin/bash", "-c"]

RUN kipoi env create MPRA-DragoNN --verbose

RUN echo "source activate kipoi-MPRA-DragoNN" > ~/.bashrc
ENV PATH /opt/conda/envs/kipoi-MPRA-DragoNN/bin:$PATH

SHELL ["conda", "run", "-n", "kipoi-MPRA-DragoNN", "/bin/bash", "-c"]

RUN conda install -c anaconda cython && pip install keras==2.3.1