FROM haimasree/kipoi-docker:kipoi-base-env

SHELL ["conda", "run", "-n", "kipoi-env", "/bin/bash", "-c"]

RUN kipoi env create DeepMEL --verbose

RUN echo "source activate kipoi-DeepMEL" > ~/.bashrc
ENV PATH /opt/conda/envs/kipoi-DeepMEL/bin:$PATH

SHELL ["conda", "run", "-n", "kipoi-DeepMEL", "/bin/bash", "-c"]

RUN pip install h5py==2.10.0