FROM haimasree/kipoi-docker:kipoi-base-env

SHELL ["conda", "run", "-n", "kipoi-env", "/bin/bash", "-c"]

RUN kipoi env create MMSplice/mtsplice --verbose

RUN echo "source activate kipoi-MMSplice__mtsplice" > ~/.bashrc
ENV PATH /opt/conda/envs/kipoi-MMSplice__mtsplice/bin:$PATH

SHELL ["conda", "run", "-n", "kipoi-MMSplice__mtsplice", "/bin/bash", "-c"]