FROM haimasree/kipoi-docker:kipoi-base-env

SHELL ["conda", "run", "-n", "kipoi-env", "/bin/bash", "-c"]

RUN kipoi env create deepTarget --verbose

RUN echo "source activate kipoi-deepTarget" > ~/.bashrc
ENV PATH /opt/conda/envs/kipoi-deepTarget/bin:$PATH

SHELL ["conda", "run", "-n", "kipoi-deepTarget", "/bin/bash", "-c"]
