FROM haimasree/kipoi-docker:kipoi-base-env


SHELL ["conda", "run", "-n", "kipoi-env", "/bin/bash", "-c"]

RUN kipoi env create AttentiveChrome --verbose

RUN echo "source activate kipoi-AttentiveChrome" > ~/.bashrc
ENV PATH /opt/conda/envs/kipoi-AttentiveChrome/bin:$PATH

SHELL ["conda", "run", "-n", "kipoi-AttentiveChrome", "/bin/bash", "-c"]