FROM kipoi-base-env:0.1

ADD ./tests/test-shared-py3-keras2.py /tmp/test-shared-py3-keras2.py

SHELL ["conda", "run", "-n", "kipoi-env", "/bin/bash", "-c"]

RUN kipoi ls && kipoi env create shared/envs/kipoi-py3-keras2

RUN echo "source activate kipoi-shared__envs__kipoi-py3-keras2" > ~/.bashrc
ENV PATH /opt/conda/envs/kipoi-shared__envs__kipoi-py3-keras2/bin:$PATH

SHELL ["conda", "run", "-n", "kipoi-shared__envs__kipoi-py3-keras2", "/bin/bash", "-c"]
