FROM continuumio/miniconda3:latest as build

RUN conda install -y -c conda-forge conda-pack conda-libmamba-solver && \
    # conda install pip pkgconfig conda-forge::hdf5 && \
    pip install kipoi && \
    kipoi env create APARENT/site_probabilities --source=kipoi 
    # && \
    # conda clean -afy

WORKDIR /kipoi-APARENT__site_probabilities
RUN conda-pack -n kipoi-APARENT__site_probabilities -o /tmp/kipoi-APARENT__site_probabilities.tar --ignore-missing-files && \
    tar xf /tmp/kipoi-APARENT__site_probabilities.tar && \
    rm /tmp/kipoi-APARENT__site_probabilities.tar

FROM debian:bullseye-slim   

RUN apt-get update && apt-get install --no-install-recommends -y ca-certificates git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app
COPY --from=build /kipoi-APARENT__site_probabilities /opt/conda/envs/kipoi-APARENT__site_probabilities

SHELL ["/bin/bash", "-c"]
RUN echo "source /opt/conda/envs/kipoi-APARENT__site_probabilities/bin/activate" > ~/.bashrc
ENV PATH /opt/conda/envs/kipoi-APARENT__site_probabilities/bin:$PATH

SHELL ["conda", "run", "-n", "kipoi-APARENT__site_probabilities", "/bin/bash", "-c"]


