FROM kipoi/kipoi-docker:kipoi-base-env

SHELL ["conda", "run", "-n", "kipoi-env", "/bin/bash", "-c"]

RUN kipoi env create MMSplice/deltaLogitPSI --verbose

RUN echo "source activate kipoi-MMSplice__deltaLogitPSI" > ~/.bashrc
ENV PATH /opt/conda/envs/kipoi-MMSplice__deltaLogitPSI/bin:$PATH

SHELL ["conda", "run", "-n", "kipoi-MMSplice__deltaLogitPSI", "/bin/bash", "-c"]
